---
services:
  docker:
    image: "docker:dind-rootless"
    container_name: "dind_rootless"
    restart: unless-stopped
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './data/dind/sock:/run/user/1000'
      - './data/dind/varlibdocker:/home/rootless/.local/share/docker'
      - './data/jenkins/slave:/var/jenkins_home'
    privileged: true
  slave:
    image: simenduev/jenkins-auto-slave:latest
    container_name: "jenkins_slave"
    restart: unless-stopped
    depends_on:
      - docker
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './data/jenkins/slave:/var/jenkins_home'
      - './data/dind/sock:/docker-sock'
    environment:
      JENKINS_URL: "https://jenkins.internal.domain"
      JENKINS_AGENT_CONNECTION_MODE: -webSocket
      JENKINS_AGENT_NAME: "builder"
      JENKINS_AUTH: "registrator:1234567890123456789012"
      JENKINS_AGENT_NUM_EXECUTORS: "2"
      DOCKER_HOST: unix:///docker-sock/docker.sock
